# Generated by Django 4.1 on 2022-10-27 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_alter_prestamo_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha',
        ),
        migrations.CreateModel(
            name='EstadoPrestamo',
            fields=[
                ('idEstadoPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('idPrestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.prestamo')),
            ],
        ),
    ]
